### PR TITLE
Converting to ZenPack with a Notification

### PR DESCRIPTION
**Pull request by jregovic**
I took the liberty of figuring out how to make this into a notification that you can use with a drop down. I like the way the messages work, I just wanted to be able to choose slack from the action type in the drop down.

The original slack_zenoss code is slightly modified in the lib directory to take arguments from the action.

### CODE REVIEW

**Comment by ssplatt** [comment]
I really like the idea of a proper Zenpack, thanks for taking the time to develop one. Hopefully I'll be able to test this out soon and merge your work.

**Comment by jregovic** [comment]
Glad I can help! I experienced the SSL handshake problem the other day and added disable_ssl_certificate_validation=True, thought the issue was using our proxy.

**Comment by ssplatt** [comment]
I'm hitting "ImportError: No module named socks". Is there a module that needs to be installed manually?

**Comment by ssplatt** [comment]
I fixed that error by running /opt/zenoss/easy_install pip; pip install PySock;  but now I'm hitting the SSL error again.  Is there a way to add something to the setup.py to make sure PySock is installed?

i also don't see this "disable_ssl_certificate_validation=True" anywhere. did that get pushed?

**Comment by jregovic** [comment]
With this commit, yes, but now I realize that a separate socks library is unecessary.

I am will test this again and add a fix.

**Comment by jregovic** [comment]
I think that socks is installed  with zenoss as a part of httplib2, so installing PySock isn't necessary. 

I will double check that. I will try and get the corrections pushed today.

**Comment by ssplatt** [comment]
hmm. well I had httplib2 installed already so I'm not sure why 'socks' wasn't there before then.

**Comment by jregovic** [comment]
I only discovered by doing a locate socks and found:

/opt/zenoss/lib/python/httplib2/socks.py

and found that  
from httplib2 import socks 

works

**Comment by jregovic** [comment]
OK, I've fixed the Socks issue and added the disable_ssl_certificate_validation.

**Comment by ssplatt** [comment]
excellent. looks like it's all working. merging request

**Pull request merged**
